export enum POPUP_TYPE {
    SWAP_CONFIRM = 'SWAP_CONFIRM',
    BROADCASTED = 'BROADCASTED',
    SWAP_SUCCESS = 'SWAP_SUCCESS',
    SWAL_POPUP = 'SWAL_POPUP',
    CONFIRM_ADD_WALLET_POPUP = 'CONFIRM_ADD_WALLET_POPUP',
    ADD_WALLET_POPUP = 'ADD_WALLET_POPUP',
}
